### ISSUE TITLE
缺少配置文件

### ISSUE THREAD

**Issue by zhouzongyan** [white0dew/OfferNow#1]
你好，没有看到.env.local配置文件，命令执行不了，请问一下里面的配置格式是啥

![image](https://github.com/user-attachments/assets/a473d622-fe37-4774-81c1-823b1c908505)

**Comment by white0dew** [comment]
> 你好，没有看到.env.local配置文件，命令执行不了，请问一下里面的配置格式是啥
> 
> ![image](https://private-user-images.githubusercontent.com/18110319/350820340-a473d622-fe37-4774-81c1-823b1c908505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjY1MjIsIm5iZiI6MTcyMjQyNjIyMiwicGF0aCI6Ii8xODExMDMxOS8zNTA4MjAzNDAtYTQ3M2Q2MjItZmUzNy00Nzc0LTgxYzEtODIzYjFjOTA4NTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExNDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNGU4YjRkNThlYWIzYTkzZTlkNDQ3NGVjYTZkZTRiYzNlYWYzYWE3NmRjYzcyZTA5NDE4YWMwYjJkOGU0ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZ2vlU77gHFv01I-W9uGM4E9cyuC4yKl7INnogvLfWo)

很好的问题，我新增一个env.example吧

**Comment by white0dew** [comment]
> 你好，没有看到.env.local配置文件，命令执行不了，请问一下里面的配置格式是啥
> 
> ![image](https://private-user-images.githubusercontent.com/18110319/350820340-a473d622-fe37-4774-81c1-823b1c908505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjY2ODcsIm5iZiI6MTcyMjQyNjM4NywicGF0aCI6Ii8xODExMDMxOS8zNTA4MjAzNDAtYTQ3M2Q2MjItZmUzNy00Nzc0LTgxYzEtODIzYjFjOTA4NTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExNDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjA2OGFkYzEwOTU5ODgyMTcyNmZmNWZmMDE0MGZiYzY5MGJlMWQ0YWFiMGY0NWVkMjFmNDFmNTFiZmY2NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BFxVjG8h64rpGtN4DQWpZcsa7KtnvlokEO4JvhBVpvA)

已上传
